### ISSUE TITLE
Adding a reverse geocode to a 

### ISSUE THREAD

**Issue by ianweb1000** [pbugnion/gmaps#274]
I am trying to insert a reverse geocode into the  class that responds to other widgets. In other words 
I am trying to insert or bind:
-4.1 Reacting to user actions on the map ( in the documentation)
-4.2Updating data in response to other widgets ( in the documentation)

Is this possible?

I would post my code but its really bi. However if needed please let me know and i will be happy to post.

Regards

Ian

**Comment by pbugnion** [comment]
Thanks for raising this.

How is what you're trying to do different to the reverse geocoder example in the documentation?

> I would post my code but its really big

Please don't post lots of code. If you want help, try to come up with a *minimal* example demonstrating what's not working, or which parts are unclear.

**Comment by pbugnion** [comment]
You react to clicks through the `self._new_feature_callback` method (the name doesn't matter, but that's the name you bound `self._drawing.on_new_feature`). This means that, every time someone clicks on the map, `self._new_feature_callback` is called.

You need to implement `self._new_feature_callback` so that it:
- clears `self._address_box` if there is something in it already
- extracts the address from the geocoder
- writes the address to `self._address_box`.

Follow the flow of `_new_feature_callback` in the [example](https://jupyter-gmaps.readthedocs.io/en/latest/app_tutorial.html#reacting-to-user-actions-on-the-map) -- it does exactly that.

**Comment by pbugnion** [comment]
Closing this. Feel free to reopen if you come across an issue, or just carry on commenting here if you need help.
