### ISSUE TITLE
unable  see any maps

### ISSUE THREAD

**Issue by ajelenic** [pbugnion/gmaps#282]
HI,
Newby here.

I believe that i was able to authenticate properly since
1)gmaps.configure(api=os.environ("GOOGLE_API_KEY" does not raise a warning or an error.
2) I am able to view the various google datasets for example earthquake_df ( in the earthquake example)
I am able to view these in Jupyter as the df show up in the next cell.

3) All of the other sample code for gmap run without error ( for example the taxi example, and the earthquake example), but I am not able to see an embedded map and an error is not raised.

for example when i type ""fig" in jupyter nothing happens

In my google API I have enable embedded maps and other map api in an effort to fix my issue.
I have no idea why I am failing, as viewing the databases works well.
My internet connection is very fast (>20Mb/s), so i dont think this is an issue of not being patient for the map to render

I installed gmaps through the conda install. my conda is up to date.

I use chrome as a browser and firefox. both of them do not yield any maps. I tried setting each of them as default. It made no difference.

I also was unable to view any maps using Jupyter Labs.
Do I need to write a % inline somewhere?
Maybe I did something wrong during authentication, as I never did that before.

**Comment by pbugnion** [comment]
Thanks for raising this.

The problem is unlikely to be an authentication one. It's more likely that the Jupyter frontend hasn't picked up the jupyter-gmaps extension.

Are you using JupyterLab? If so, have you followed the JupyterLab specific [installation instructions](https://jupyter-gmaps.readthedocs.io/en/latest/install.html#installing-jupyter-gmaps-for-jupyterlab)?

**Comment by ajelenic** [comment]
After restarting windows,
I get some output such as this in the reverse geocoder example

VBox(children=(Figure(layout=FigureLayout(height='420px')), Text(value='', description='Address: ', disabled=T…

Here is my starbucks example with output 
![gmap](https://user-images.githubusercontent.com/20255775/50377278-3ae2bb80-05e8-11e9-97c4-960c73a0c76e I1.PNG)


In the gmaps installation guide:
You must have NPM to install the development version. You can install NPM with your package manager.

I didnt install NPM because in my opinion i dont want that version. Is that a mistake? 
Other than that i did everything in the installation including putting the API key in my environment variables. Maybe I chose the wrong APIs for my key. I was a little unsure about that part, so i have attached a screen shot of the API and quotas I setup
![google api](https://user-images.githubusercontent.com/20255775/50377310-176c4080-05e9-11e9-9ea5-21e332188a13.PNG)

**Comment by pbugnion** [comment]
I'm almost completely sure this has nothing to do with your keys. When you have incorrect keys, you still see a map, but it's greyed out.

It's much more likely because something went wrong during the installation process. Bear in mind that, to make gmaps work with JupyterLab, you need to do more than just `conda install gmaps -c conda-forge`.

Have you run:

```
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter lab build
```
... as mentioned in the [installation instructions for JupyterLab](https://jupyter-gmaps.readthedocs.io/en/latest/install.html#installing-jupyter-gmaps-for-jupyterlab)?

**Comment by ajelenic** [comment]
This fixed my issue 100%
I am able to see google earth in my scripts.  
In my previous attempts i did not include the labextension install
Thank you Pascal!!

**Comment by pbugnion** [comment]
Great, glad that helped.
