### ISSUE TITLE
support only about 1500 points. Doesn't work for more points

### ISSUE THREAD

**Issue by beizhao215** [pbugnion/gmaps#55]
I have a list of 200,000 lat,lon pairs. The heatmap works fine until 1500 points. When set to 2000, it just show a regular map without heat. Is that there's a limit on how many points can be supported?

The code is running on jupyter in datascientist workbench with spark

import gmaps

longitude_list = sqlContext.sql("SELECT lon From table_15_1")
latitude_list = sqlContext.sql("SELECT lat From table_15_1")
data = []
for lat,lon in zip(latitude_list.collect()[:2000], longitude_list.collect()[:2000]):
      point = []
      point.append(lat)
      point.append(lon)
      data.append(point)
gmaps.heatmap(data)

**Comment by pbugnion** [comment]
Very much failing to verify this.

The following should work out of the box, using earthquake data that's boxed in with gmaps:

```
data = gmaps.datasets.load_dataset("earthquakes")
print(len(data)) # 8604
gmaps.heatmap(data)
```

In fact, I've tested this with 100,000 with no noticeable problems. It started taking too long to render when I hit much higher numbers, though.

The map failing to plot is usually caused by an error in the dataset. Unfortunately, Google maps just fails silently if you pass in data that it can't plot (e.g. non-numeric data) and this library doesn't do much checking client-side.

I suggest you try and isolate the point that is causing trouble and make sure that it's a valid longitude / latitude pair. If the problem persists, I suggest you attach a csv of the data (or as small a subset of the data as possible to reproduce the problem) to this.
