### ISSUE TITLE
Ability to save maps as images.

### ISSUE THREAD

**Issue by xoolive** [pbugnion/gmaps#62]
It would probably be a nice thing to have something like:

``` python
import gmaps
m = gmaps.Map()
m.add_layer(...)
m.save("map.png")
```

`Google Static Maps API` may help? It would be nice to investigate.

**Comment by pbugnion** [comment]
Definitely. I've looked into the static API before and decided it wasn't suitable, but I can't remember why. Anyway, saving a map to PNG or exporting to HTML would definitely be useful.

**Comment by reyale** [comment]
The static maps api appears to have limitations on the number of elements it can renders, because the query string has length restrictions (2048 characters).

**Comment by pbugnion** [comment]
@reyale that's useful to know, thanks.

**Comment by lincolnfrias** [comment]
a big +1 on this feature.

**Comment by alebu** [comment]
+1 on this

**Comment by Canas** [comment]
Definitely would love this, since ipyleaflets doesn't have this feature either.

**Comment by pbugnion** [comment]
I agree this would be really valuable. I just don't know how to approach this. AFAICT, there are two possible strategies: 

- the [Google Maps static API](https://developers.google.com/maps/documentation/static-maps/intro)) mentioned above. This suffers from a limitation on query string length (now 8192 characters), which limits the complexity of data, as well as needing significant extra work in *jupyter-gmaps* for every new layer.

- using something like [html2canvas](https://github.com/niklasvh/html2canvas) to just export the div that the map is rendered in. I think this would be better done at the widgets level, rather than in *jupyter-gmaps* itself, so I've raised an [issue](https://github.com/jupyter-widgets/ipywidgets/issues/1291) with the maintainers.

**Comment by pbugnion** [comment]
A possible strategy for tackling this problem is:

 - check that `html2canvas` can be used to export google maps. There's a [SO question](http://stackoverflow.com/questions/16235161/save-current-google-map-as-image) about this with several examples in the answers. It's probably easiest to test that outside of the context of Jupyter.

 - if that works, embed a button in the frontend to export the map. We can probably ~~copy~~ draw inspiration from [bqplot](https://github.com/bloomberg/bqplot) for this.

**Comment by pbugnion** [comment]
Users can now export maps as PNG, but see issue #129 for limitations.
